networks:
  techshop_shared-network:
    driver: bridge
    name: techshop_shared-network

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: techshop-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - techshop_shared-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: techshop-kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - techshop_shared-network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: techshop-kafdrop
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29093
    networks:
      - techshop_shared-network

  techshop-message-producer:
    image: openjdk:21-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techshop-message-producer
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29093
    ports:
      - 8080:8080
    networks:
      - techshop_shared-network
