spring:
  kafka:
    producer:
      bootstrap-servers: kafka:29093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

topic: orders
products.file: products.txt
customers.file: customers.txt
addresses.file: addresses.txt
